apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-api
spec:
  selector:
    matchLabels:
      app: sales-api
  template:
    metadata:
      labels:
        app: sales-api
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      containers:
      - name: zipkin
        image: openzipkin/zipkin-slim:2.21
        ports:
        - name: zipkin
          containerPort: 9411
        resources: {}
      - name: app
        image: eu.gcr.io/tullo-starter-kit/sales-api-amd64:1.0
        ports:
        - name: app
          containerPort: 3000
        - name: app-debug
          containerPort: 4000
        resources: {}
      - name: metrics
        image: eu.gcr.io/tullo-starter-kit/metrics-amd64:1.0
        ports:
        - name: metrics
          containerPort: 3001
        - name: metrics-debug
          containerPort: 4001
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: sales-api
spec:
  selector:
    app: sales-api
  ports:
  - name: app
    port: 3000
    protocol: TCP
    targetPort: 3000
