apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./staging-config.yaml
- ../base
patchesStrategicMerge:
- env-patch.yaml
- images-patch.yaml
- loadbalancer-patch.yaml
- secrets-patch.yaml
- replicas-patch.yaml
secretGenerator:
- envs:
  - .env-db
  name: stackwise
  type: Opaque
images:
- name: eu.gcr.io/stackwise-starter-kit/sales-api-amd64
  newName: eu.gcr.io/stackwise-starter-kit/sales-api-amd64
  newTag: fc91632512b4b318ae13a2aea52f7b31dc54aa16
