apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: sales-api
  template:
    metadata:
      name: sales-api
      labels:
        service: sales-api
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: sales-api
        image: tullo/sales-api-amd64:1.0
        env:
        - name: SALES_DB_HOST
          value: postgresql
        - name: SALES_DB_NAME
          value: okteto
        - name: SALES_DB_USER
          value: okteto
        - name: SALES_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: postgresql-password
        - name: SALES_DB_DISABLE_TLS
          value: "true"
        - name: SALES_ZIPKIN_REPORTER_URI
          value: http://zipkin:8080/api/v2/spans
        ports:
        - name: sales-api
          containerPort: 8080
        - name: debug
          containerPort: 4000
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /v1/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /v1/health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
      - name: metrics
        image: tullo/metrics-amd64:1.0
        env:
        - name: METRICS_COLLECT_FROM
          value: "http://localhost:4000/debug/vars"
        ports:
        - name: metrics
          containerPort: 3001
        - name: debug
          containerPort: 4001
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: sales-api
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
  - name: "zipkin"
    port: 9411
    targetPort: 9411
  - name: "sales-api"
    port: 8080
    targetPort: 3000
  - name: "sales-api-debug"
    port: 4000
    targetPort: 4000
  - name: "metrics"
    port: 3001
    targetPort: 3001
  - name: "metrics-debug"
    port: 4001
    targetPort: 4001
  selector:
    service: sales-api
