apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
spec:
  replicas: 1
  selector:
    matchLabels:
      service: search
  template:
    metadata:
      name: search
      labels:
        service: search
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: search
        image: registry.cloud.okteto.net/tullo/search-amd64:1.0
        env:
        - name: SEARCH_SALES_ENDPOINT
          value: http://sales-api:8080/v1/products
        - name: SEARCH_ZIPKIN_REPORTER_URI
          value: http://zipkin:8080/api/v2/spans
        ports:
        - name: search
          containerPort: 8080
        - name: debug
          containerPort: 6000
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: search
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
  - name: "sales-api"
    port: 8080
    targetPort: 5000
  selector:
    service: search