# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
 version: 2
 jobs:
   build:
     machine:
       image: ubuntu-1604:201903-01
     steps:
       - checkout
       - run:
           name: Install Go 1.15
           command: |
               sudo rm -rf /usr/local/go
               wget -O go.tgz https://dl.google.com/go/go1.15.linux-amd64.tar.gz
               sudo tar -C /usr/local -xzf go.tgz
               rm go.tgz
               which go
               go version
       - run:
           name: Download the DB image used in tests
           command: docker pull postgres:12.4-alpine
       - run:
           name: Run tests
           command: 
               go test -v ./...
