apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app-config.yaml
  - ../base
  - postgres.yaml
patchesStrategicMerge:
- env-patch.yaml
- replicas-patch.yaml
- rollout-strategy-patch.yaml

