# https://github.com/compose-spec/compose-spec/blob/master/spec.md
version: '3.9' # optional since Compose v1.27.0

networks:
  shared-network:
    driver: bridge

services:

  db:
    container_name: sales_db
    image: cockroachdb/cockroach:v23.2.1
    command: start-single-node --advertise-addr 'localhost' --insecure
    healthcheck:
      test: ["CMD", "/cockroach/cockroach", "node", "status", "--insecure"]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      shared-network:
    ports:
    - published: 8080
      target: 8080
    - published: 26257
      target: 26257
    volumes:
    - crdb_data:/cockroach/cockroach-data

  # Publishes metrics to the console by default.
  metrics:
    container_name: metrics
    image: ${REGISTRY_ACCOUNT}/metrics-amd64:${VERSION}
    networks:
      shared-network:
    ports:
    - published: 3001 # EXPVAR API
      target: 3001
    - published: 4001 # DEBUG API
      target: 4001
    user: '100000'

  # This is the core CRUD based service.
  sales-api:
    container_name: sales-api
    depends_on:
      db:
        condition: service_healthy
      metrics:
        condition: service_started
      zipkin:
        condition: service_healthy
    environment:
      #GODEBUG=gctrace: '1'
      POSTGRES_PASSWORD: postgres
      SALES_DB_DISABLE_TLS: '1' # Disabled for development.
      SALES_DB_HOST: 'db:26257'
      SALES_DB_USER: 'admin'
      SALES_ZIPKIN_PROBABILITY: '1' # 100% recording and sampling
    healthcheck:
      test:
      - CMD-SHELL
      - wget --spider http://localhost:4000/debug/readiness
      interval: 10s
      retries: 3
      timeout: 5s
    image: ${REGISTRY_ACCOUNT}/sales-api-amd64:${VERSION}
    networks:
      shared-network:
    ports:
    - published: 3000 # CRUD API
      target: 3000
    - published: 4000 # DEBUG API
      target: 4000
    user: '100000'

  # Examination of traces.
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin-slim:3.0
    networks:
      shared-network:
    ports:
    - published: 9411
      target: 9411
    user: '1000'

volumes:
  crdb_data: {}