# https://docs.docker.com/compose/compose-file
# docker-compose up
# docker-compose stop
# docker-compose down
version: '3.8'

networks:
  shared-network:
    driver: bridge

services:

  # This starts a local PostgreSQL DB.
  db:
    container_name: sales_db
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres:13.2-alpine
    networks:
      shared-network:
    ports:
    - published: 5432
      target: 5432

  # This sidecar publishes metrics to the console by default.
  metrics:
    container_name: metrics
    image: ${REGISTRY_ACCOUNT}/metrics-amd64:${VERSION}
    networks:
      shared-network:
    ports:
    - published: 3001 # EXPVAR API
      target: 3001
    - published: 4001 # DEBUG API
      target: 4001
    user: '100000'

  # This is the core CRUD based service.
  sales-api:
    container_name: sales-api
    depends_on:
      db:
        condition: service_started
      metrics:
        condition: service_started
      zipkin:
        condition: service_started
    environment:
      #GODEBUG=gctrace: '1'
      POSTGRES_PASSWORD: postgres
      SALES_DB_DISABLE_TLS: '1' # This is only disabled for our development enviroment.
      SALES_DB_HOST: db
      SALES_ZIPKIN_PROBABILITY: '1' # 100% recording and sampling
    image: ${REGISTRY_ACCOUNT}/sales-api-amd64:${VERSION}
    networks:
      shared-network:
    ports:
    - published: 3000 # CRUD API
      target: 3000
    - published: 4000 # DEBUG API
      target: 4000
    user: '100000'

  # This sidecar allows for examination of traces.
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin-slim:2.22
    networks:
      shared-network:
    ports:
    - published: 9411
      target: 9411
    user: '1000'
