apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./stg-config.yaml
  - ../base
patchesStrategicMerge:
  - env-patch.yaml
  - images-patch.yaml
  - loadbalancer-patch.yaml
  - replicas-patch.yaml
